name: E2E Test
on:
  push:

jobs:
  test:
    defaults:
      run:
        working-directory: ./App
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./App/playwright/results
